Error with array indexing fixed
oleville/front-page-calendar pull request #2
Opened 2017-09-08 17:44 UTC by neko3791

The array for days of the week within calendar-tile.js begins with Monday at 0. If the event info that the calendar draws from indexes with Monday at 1, the days would be rendered incorrectly here. If the error is fixed at the source, the change is unnecessary. Unsure whether this is the case, but it's my best guess.

2017-09-08 18:35 UTC, erichkauffman requested changes
This is a good thought, but adding 1 to the day will put the index out of range if ```day()``` returns a 6. After doing a little reading on moment.js, it looks like ```day()``` returns 0-6, 0 being Sunday and 6 being Saturday. This means that the order of days in ```DAYS_OF_WEEK``` array does not match the return of ```day()```. I would recommend putting Sunday at the beginning of the array instead of changing the calculations.

2017-09-08 18:42 UTC, elijahverdoorn requested changes

2017-09-08 18:42 UTC, elijahverdoorn commented on src/calendar-tile.js
> +			startDate: !overOneWeek ? DAYS_OF_WEEK[startMoment.day()+1] : startMoment.format('MMM Do'),
I agree with Erich. Here's a link that might be helpful: https://momentjs.com/docs/#/get-set/day/

2017-09-10 18:04 UTC, neko3791 commented
Alright, I reordered the array and undid my previous change. Does this work?

2017-09-10 18:32 UTC, erichkauffman approved these changes
👍  Looks good!

2017-09-11 19:28 UTC, elijahverdoorn approved these changes
You really shouldn't be asking us "does this work", you should say "this works, and here's why I think this is better than what we have now". Having said that, this is a bugfix that we agree should happen, and this does indeed work.

2017-09-12 01:55 UTC, merged

2017-09-12 02:49 UTC, elijahverdoorn commented
@erichkauffman @neko3791 We can talk at the meeting tomorrow about how to deploy this.